backend:
  name: github
  repo: renatadibernardi/astro-blog-starter-template
  branch: main
  base_url: https://decap-auth.dibernardi.workers.dev
  auth_endpoint: /auth

locale: pt

media_folder: public/images/uploads
public_folder: /images/uploads

publish_mode: editorial_workflow

collections:
  - name: blog
    label: Artigos
    label_singular: Artigo
    folder: src/content/blog
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"

    fields:
      - label: Título do artigo
        name: title
        widget: string

      - label: Descrição
        name: description
        widget: text

      - label: Categoria
        name: category
        widget: select
        required: false
        options:
          - { label: "Identidade em Deus", value: "identidade-em-deus" }
          - { label: "Sinal x Identidade", value: "sinal-x-identidade" }

      - label: Data de publicação
        name: pubDate
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ssZ"
        picker_utc: true

      - label: Imagem principal
        name: heroImage
        widget: image
        required: false

      - label: Conteúdo do artigo
        name: body
        widget: markdown

  - name: link
    label: Links
    label_singular: Link
    folder: src/content/link
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"

    fields:
      - label: Nome
        name: name
        widget: string

      - label: URL
        name: link
        widget: string

      - label: Descrição
        name: description
        widget: text
        required: false

      - label: Data de criação
        name: createdAt
        widget: datetime
        format: "YYYY-MM-DDTHH:mm:ss.SSSZ"
        picker_utc: true

      - label: Tags
        name: tags
        widget: list
        default: []

      - label: Bundles
        name: bundles
        widget: list
        default: []

      - label: Favorito
        name: favorite
        widget: boolean
        default: false

      - label: Favicon (URL)
        name: favicon
        widget: string
        required: false

      - label: Imagem de preview (URL)
        name: ogthumb
        widget: string
        required: false

      - label: Criador
        name: creator
        widget: string
        default: dibernardi